### ISSUE TITLE
SFZ missing after cloning

### ISSUE THREAD

**Issue by joex92** [sgossner/VSCO-2-CE#12]
Hi, I tried using the cloning method: `git clone https://github.com/sgossner/VSCO-2-CE.git`
but after doing that I got everything but the SFZ files:
![image](https://user-images.githubusercontent.com/645579/170895865-6ea3bcf3-7e35-4b8c-ae3a-458820b59123.png)
![image](https://user-images.githubusercontent.com/645579/170895911-b566d49e-fe18-46e0-a91e-a7c1968cf167.png)
so how do I download them without redownloading everything again? (the zip file has everything)

**Comment by sgossner** [comment]
You need to switch to the SFZ branch. The Master branch just contains the sample files only (the main part of the project).

**Comment by joex92** [comment]
oh ok, yeah, there wasn't a way to only download the SFZ files, so I had to redownload everything...
So I did this:
`git clone --branch SFZ https://github.com/sgossner/VSCO-2-CE.git`
and got the files... thanks...

**Comment by sgossner** [comment]
> oh ok, yeah, there wasn't a way to only download the SFZ files, so I had to redownload everything... So I did this: `git clone --branch SFZ https://github.com/sgossner/VSCO-2-CE.git` and got the files... thanks...

Thanks, I've updated the instructions on the Release to help any future users avoid this issue.
