### ISSUE TITLE
Incorrect paths in sfz

### ISSUE THREAD

**Issue by peastman** [sgossner/VSCO-2-CE#4]
A few sfz files have paths that incorrectly start with a \ character.  For example

```
default_path=\Percussion\
```

That should be

```
default_path=Percussion\
```

This causes an error when you try to load it in Sforzando, at least on Mac OS.  This problem appears in four files: Marimba.sfz, TubularBells.sfz, FluteSusVib.sfz, and Flute-KS.sfz.

**Comment by sgossner** [comment]
Fixed all, thanks! Fix should be all sync'd up with the SFZ branch now.
